name: CI_Build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-2019", "macos-latest", "windows-latest"]
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: make bin on ${{ matrix.os }}
      run: | 
        mkdir build 
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"
        make bin
    - name: test bin on ${{ matrix.os }}
      run: |
        cd build
        ctest -R bin --verbose
    - name: make lib on ${{ matrix.os }}
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"
        make lib
    - name: test lib on ${{ matrix.os }}
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug -G "Unix Makefiles"        
        make lib_test_c
        ctest -R lib --verbose
